# docker-compose.yml
version: "3"
services:
  db:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manipulation